export type NavSection = "Home" | "Analytics" | "Tasks" | "Manage";

// Section order + which ones show a group label (Home is unlabeled — it's the
// landing item at the very top).
export const NAV_SECTIONS: { key: NavSection; label?: string }[] = [
  { key: "Home" },
  { key: "Tasks", label: "Tasks" },
  { key: "Analytics", label: "Analytics" },
  { key: "Manage", label: "Manage" },
];

export type NavItem = {
  title: string;
  href: string;
  icon: string;
  section: NavSection;
  showBadge?: boolean;
  // Hidden from the sidebar (and its topbar shortcut, where one exists) for
  // anyone who isn't an admin.
  adminOnly?: boolean;
};

export const NAV_ITEMS: NavItem[] = [
  { title: "Home", href: "/home", icon: "🏠", section: "Home" },
  { title: "Dashboard", href: "/dashboard", icon: "📊", section: "Analytics" },
  // Insights, Trends, Reports — hidden from the sidebar per request; routes/
  // pages still exist (see App.tsx, PAGE_META below), just not linked.
  { title: "Top Performers", href: "/top", icon: "🥇", section: "Analytics" },
  { title: "Leaderboard", href: "/leaderboard", icon: "🏆", section: "Analytics" },
  { title: "Task Board", href: "/tasks", icon: "✅", section: "Tasks" },
  { title: "Social & Ads Pipeline", href: "/metrics", icon: "🎬", section: "Tasks" },
  { title: "Task Settings", href: "/task-rules", icon: "🛠️", section: "Tasks", adminOnly: true },
  // Social Media, Activity — hidden from the sidebar per request; routes/
  // pages still exist.
  { title: "Add Post", href: "/posts/new", icon: "➕", section: "Manage", adminOnly: true },
  { title: "Posts", href: "/posts", icon: "🗂️", section: "Manage", showBadge: true },
  { title: "Channels", href: "/channels", icon: "🌐", section: "Manage" },
  { title: "Teams", href: "/teams", icon: "🧑‍🤝‍🧑", section: "Manage" },
  { title: "Settings", href: "/settings", icon: "⚙️", section: "Manage" },
];

// Page title + subtitle shown in the topbar, keyed by pathname.
export const PAGE_META: Record<string, [string, string]> = {
  "/home": ["Home", "What needs your attention today"],
  "/dashboard": ["Dashboard", "Live analytics from your content data"],
  "/metrics": ["Social & Ads Pipeline", "Who's working on which Social post or Ad, and where it stands"],
  "/insights": ["Insights", "What your data is telling you — computed automatically"],
  "/trends": ["Trends", "How your content is performing over time, and platform vs platform"],
  "/top": ["Top Performers", "Your best-performing content, ranked separately for each platform"],
  "/leaderboard": ["Editor Leaderboard", "Editor performance & rankings from published posts"],
  "/reports": ["Reports", "Export and share performance summaries"],
  "/posts/new": ["Add Post", "Create the post record now — log its metrics after you publish"],
  "/posts": ["Posts", "Your content database — replaces the Manual Entry sheet"],
  "/channels": ["Channels & Platforms", "Manage channels, platforms, and Instagram sync — all in one place"],
  "/tasks": ["Task Management", "Assign and track your team's daily tasks"],
  "/social-media": ["Social Media", "Work generated by your posts, tracked per account — claim it or see who's on it"],
  "/task-rules": ["Task Settings", "Content formats and how many hours each should take, per person or org-wide"],
  "/activity": ["Activity", "Everything happening across Media House, newest first"],
  "/teams": ["Teams", "Roster, hierarchy, and login access — one place for everyone on the team"],
  "/settings": ["Settings", "Taxonomy, scoring weights, and integrations"],
  "/analytics": ["Format analytics", "Total performance across all posts of one format"],
};
